# Generated by Django 5.0.6 on 2024-06-07 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='category',
            field=models.CharField(choices=[('GE', 'GENERAL'), ('SC', 'SCIENCE'), ('TR', 'TRADE'), ('ED', 'EDUCATIONAL')], default='GE', max_length=2),
        ),
    ]
